server.port=8006
spring.application.name=unit-testing-service
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER:localhost}:8761/eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
ribbon.eureka.enabled=true
spring.devtools.restart.enabled=false
spring.output.ansi.enabled=ALWAYS
logging.level.root=INFO
logging.level.core=DEBUG
logging.level.com.example.unittesting=DEBUG
logging.pattern.console=%clr(%-5level) %clr(%-40.40logger{39}){cyan} : %msg%n
